import type { Job } from "./domain.js";
import type { Store } from "./store.js";

/** 架空企業のみ。実在社名は使わない。 */
const DEMO_JOBS: Omit<Job, "id">[] = [
  {
    employerSub: "employer-1",
    title: "Backend Engineer — Nimbus Forge",
    status: "published",
    employmentType: "full_time",
    location: "Tokyo",
    remote: true,
    salaryMin: 6000000,
    salaryMax: 9000000,
    skills: ["Go", "PostgreSQL", "Kubernetes"],
    description: "Nimbus Forge の API と求人検索基盤を Go で伸ばす役割。架空のポートフォリオ用シード。",
  },
  {
    employerSub: "employer-1",
    title: "Frontend Engineer — Harbor Pixel",
    status: "published",
    employmentType: "full_time",
    location: "Osaka",
    remote: true,
    salaryMin: 5000000,
    salaryMax: 8000000,
    skills: ["React", "TypeScript"],
    description: "Harbor Pixel の候補者向け検索 UI。ファセットとフィルタを担当する。",
  },
  {
    employerSub: "employer-1",
    title: "Platform Engineer — Cedarline Systems",
    status: "published",
    employmentType: "full_time",
    location: "Tokyo",
    remote: false,
    salaryMin: 7000000,
    salaryMax: 10000000,
    skills: ["Kubernetes", "Go", "Terraform"],
    description: "Cedarline Systems のクラスタとデプロイを守る。出社ベース。",
  },
  {
    employerSub: "employer-2",
    title: "Contract SRE — Maple Stack",
    status: "published",
    employmentType: "contract",
    location: "Remote",
    remote: true,
    salaryMin: 8000000,
    salaryMax: 12000000,
    skills: ["Kubernetes", "Terraform", "Go"],
    description: "Maple Stack の信頼性改善。契約社員。",
  },
  {
    employerSub: "employer-2",
    title: "Mobile Engineer — Blue Lantern Soft",
    status: "published",
    employmentType: "full_time",
    location: "Fukuoka",
    remote: true,
    salaryMin: 5000000,
    salaryMax: 7000000,
    skills: ["React Native", "TypeScript"],
    description: "Blue Lantern Soft のモバイルクライアント。",
  },
  {
    employerSub: "employer-2",
    title: "Data Engineer — Kitefield Digital",
    status: "published",
    employmentType: "full_time",
    location: "Tokyo",
    remote: false,
    salaryMin: 6000000,
    salaryMax: 9000000,
    skills: ["Python", "PostgreSQL"],
    description: "Kitefield Digital の集計パイプライン。個人を含まない集計のみ。",
  },
  {
    employerSub: "employer-2",
    title: "Product Designer — Paper Crane Apps",
    status: "published",
    employmentType: "part_time",
    location: "Kyoto",
    remote: true,
    salaryMin: null,
    salaryMax: null,
    skills: ["Figma"],
    description: "Paper Crane Apps の週3デザイン。年収は応相談。",
  },
  {
    employerSub: "employer-3",
    title: "TypeScript Intern — Quiet Harbor Tech",
    status: "published",
    employmentType: "internship",
    location: "Sapporo",
    remote: true,
    salaryMin: 2000000,
    salaryMax: 3000000,
    skills: ["TypeScript", "React"],
    description: "Quiet Harbor Tech の夏季インターン。架空求人。",
  },
  {
    employerSub: "employer-3",
    title: "Full-stack Engineer — Riveroak Engineering",
    status: "published",
    employmentType: "full_time",
    location: "Nagoya",
    remote: true,
    salaryMin: 6500000,
    salaryMax: 9500000,
    skills: ["Go", "React", "PostgreSQL"],
    description: "Riveroak Engineering の求人ボードと応募 API。",
  },
  {
    employerSub: "employer-3",
    title: "QA Engineer — Lumen Birch",
    status: "published",
    employmentType: "contract",
    location: "Remote",
    remote: true,
    salaryMin: 4500000,
    salaryMax: 6500000,
    skills: ["Playwright", "TypeScript"],
    description: "Lumen Birch の E2E。契約。",
  },
];

export async function seedDemoJobs(store: Store): Promise<Job[]> {
  const created: Job[] = [];
  for (const input of DEMO_JOBS) {
    created.push(await store.createJob(input));
  }
  return created;
}
